driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-22.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[apache]
      - recipe[mysql]
      - recipe[php]
      - recipe[wordpress]
    attributes:
