---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[apache]
    verifier:
      name: inspec

    attributes: