---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  cookbooks_path: ["cookbooks"]
  nodes_path: "nodes"

platforms:
  - name: ubuntu-20.04
  - name: centos-6

verifier:
  name: inspec

suites:
  - name: apache
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/integration/apache
    attributes: {}

  - name: mysql
    run_list:
      - recipe[mysql]
    verifier:
      inspec_tests:
        - cookbooks/mysql/spec
    attributes: {}

  - name: php
    run_list:
      - recipe[php]
    verifier:
      inspec_tests:
        - cookbooks/php/spec
    attributes: {}