---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec  
platforms:
  - name: centos-6
  - name: ubuntu-20.04

suites:
  - name: apache
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/integration/apache
    attributes: